name: 'Ark Re '
favicon: null
layout_spectrum: 0.15635
typography_spectrum: 0.59532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000405'
    - '#00444e'
    - '#00e5ff'
    - '#006c79'
    - '#008e9f'
  brandStrength: 0.6544370115734637
  lightness: 0.5611428278498352
  saturation: 0.5697310976684093
  rhythmicContrast: 0.15922911907546222
purpose: []
